---
title: "Correction du Devoir1"
author: "Dr Fousseyni KANE"
date: "17/10/2021"
output:
  html_document:
    df_print: paged
---
## Exercice 1

### Reponse 1:

```{r, include=FALSE}

if(!requireNamespace(c("tidyverse","dplyr", "data.table"), quietly = TRUE))
    install.packages(c("tidyverse","dplyr","data.table"))
library(data.table)
library(tidyverse)
library(dplyr)

mydata_list <-list.files(getwd() , pattern = "*txt|*csv", all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE) # ce scripte permet de creer une lite et d'assigner le nom de tous les fichiers du repertoire de travail se terminant par .txt ou .csv sous forme de chaine de charachere.


mydata = lapply(mydata_list, fread) #Importation de la liste des fichiers 


```

### Reponse 2:
```{r, a., warning=FALSE, error=FALSE, echo=FALSE}

print(paste("Les fichiers au format txt sont importés dans un objet de classe", class(mydata),"\n",
"Le fichier bltper_1x1_FR.txt contient", nrow(mydata[[1]]) ,"lignes et", ncol(mydata[[1]]), "colonnes. Les données de cette table concernent les années", min(mydata[[1]]$Year) ,"à",max(mydata[[1]]$Year),"\n",
"Le fichier bltper_1x1CAN.txt contient ", nrow(mydata[[2]]) ,"lignes et ", ncol(mydata[[2]]), "colonnes. Les données de cette table concernent les années", min(mydata[[2]]$Year) ,"à", max(mydata[[2]]$Year), "\n",
"Le fichier bltper_1x1GERM.txt contient", nrow(mydata[[3]]) ,"lignes et ", ncol(mydata[[3]]), " colonnes. Les données de cette table concernent les années", min(mydata[[3]]$Year) ,"à", max(mydata[[3]]$Year), "\n",
"Le fichier bltper_1x1UK.txt contient", nrow(mydata[[4]]) ,"lignes et ", ncol(mydata[[4]]), " colonnes. Les données de cette table concernent les années", min(mydata[[4]]$Year) ,"à", max(mydata[[4]]$Year), "\n", 
"Le fichier bltper_1x1USA.txt contient ", nrow(mydata[[5]]) ," lignes et ", ncol(mydata[[5]]), " colonnes. Les données de cette table concernent les années ", min(mydata[[5]]$Year) ,"à", max(mydata[[5]]$Year), "\n", "Le fichier au format csv contient ", nrow(mydata[[6]]) ," lignes et", ncol(mydata[[6]]), " colonnes."), sep=" ")

```

```{r, b.}

```


### Reponse 3:

```{r}

for(i in 1: (length(mydata)-1)){
  
  mydata_merge <- rbind.data.frame(mydata[[i]],mydata[[i+1]])
}
```

